"""Compiles dict/en.txt into src/spell_dict_en.h for the compose spell box.

dict/en.txt is `word<TAB>count` per line, most common first (built by
tools/build_spell_wordlist.py). This writes it in the front-coded block format
src/spell.h describes: sorted by bytes, each entry the shared-prefix length,
the rest of the word and a 0..255 log-scaled frequency, with a block index
every spell::kBlockWords words.

Runs as a PlatformIO pre: script on every build and rewrites the header only
when its content changes, so an unchanged tree does not force a rebuild. Also
runnable by hand:  python3 tools/gen_spell_dict.py

Reads:  dict/en.txt
Writes: src/spell_dict_en.h (gitignored)
"""
import math
import os
import re
import sys

try:
    Import("env")  # noqa: F821 -- injected by PlatformIO
    PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC_PATH = os.path.join(PROJECT_DIR, "dict", "en.txt")
DST_PATH = os.path.join(PROJECT_DIR, "src", "spell_dict_en.h")

BLOCK_WORDS = 32     # spell::kBlockWords
MAX_WORD = 32        # kMaxDictWord in spell.cpp
WORD_RE = re.compile(r"^[a-z']+$")


def load():
    words = {}
    with open(SRC_PATH, "r", encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            w, n = line.split("\t")
            if not WORD_RE.match(w) or len(w) > MAX_WORD:
                sys.exit(f"{SRC_PATH}:{lineno}: not a lowercase word of 1..{MAX_WORD}: {w!r}")
            words[w] = max(words.get(w, 0), int(n))
    return words


def encode(words):
    counts = words.values()
    lo, hi = math.log(min(counts)), math.log(max(counts))
    span = (hi - lo) or 1.0

    data = bytearray()
    blocks = []
    prev = b""
    for i, w in enumerate(sorted(words, key=lambda s: s.encode())):
        b = w.encode()
        if i % BLOCK_WORDS == 0:
            blocks.append(len(data))
            p = 0
        else:
            p = 0
            while p < min(len(b), len(prev), 15) and b[p] == prev[p]:
                p += 1
        suffix = b[p:]
        if len(suffix) < 15:
            data.append((p << 4) | len(suffix))
        else:
            data.append((p << 4) | 15)
            data.append(len(suffix))
        data += suffix
        data.append(round((math.log(words[w]) - lo) / span * 255))
        prev = b
    return data, blocks


def render(data, blocks, count):
    lines = [
        "// Generated by tools/gen_spell_dict.py from dict/en.txt -- do not edit.",
        "// Word list: hermitdave/FrequencyWords (OpenSubtitles 2018), CC-BY-SA-4.0.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const uint32_t kSpellEnWords = {count};",
        f"static const uint32_t kSpellEnSize = {len(data)};",
        "static const uint8_t kSpellEnData[] = {",
    ]
    for i in range(0, len(data), 24):
        lines.append("    " + ",".join(str(x) for x in data[i:i + 24]) + ",")
    lines.append("};")
    lines.append(f"static const uint32_t kSpellEnBlocks[{len(blocks)}] = {{")
    for i in range(0, len(blocks), 12):
        lines.append("    " + ",".join(str(x) for x in blocks[i:i + 12]) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    words = load()
    data, blocks = encode(words)
    text = render(data, blocks, len(words))
    old = None
    if os.path.isfile(DST_PATH):
        with open(DST_PATH, "r", encoding="utf-8") as fh:
            old = fh.read()
    if old != text:
        with open(DST_PATH, "w", encoding="utf-8") as fh:
            fh.write(text)
    print(f"spell: {len(words)} words, {len(data) + 4 * len(blocks)} bytes")


main()
